name: Upload to S3
on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Paths filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'site/docs/**'

  upload:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-1"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        working-directory: ./site

      - name: Build CSS files
        run: npm run build
        working-directory: ./site

      - name: Upload to S3
        run: |
          aws s3 sync ./site/docs/ s3://${{ secrets.AWS_S3_BUCKET }}

